trigger:
- master

stages:

- stage: test
  displayName: Test
  jobs:

  - template: scripts/build.yml
    parameters:
      name: Linux_net50
      displayName: Linux - net5.0
      framework: net5.0
      appFramework: net5.0
      pool:
        vmImage: 'ubuntu-latest'

  - template: scripts/build.yml
    parameters:
      name: macOS_net50
      displayName: macOS - net5.0
      framework: net5.0
      appFramework: net5.0
      pool:
        vmImage: 'macOS-latest'

  - template: scripts/build.yml
    parameters:
      name: Windows_net50
      displayName: Windows - net5.0
      framework: net5.0
      appFramework: net5.0
      pool:
        vmImage: 'windows-latest'

  - template: scripts/build.yml
    parameters:
      name: Windows_net47
      displayName: Windows - net47
      framework: net47
      appFramework: net47
      pool:
        vmImage: 'windows-latest'

- stage: pack
  displayName: Pack
  dependsOn: test
  jobs:

  - template: scripts/pack.yml
    parameters:
      name: 'pack_preview'
      displayName: 'Pack Certes preview'
      projectName: 'Certes'
      previewPackage: 'true'

  - template: scripts/pack.yml
    parameters:
      name: 'pack'
      displayName: 'Pack Certes'
      projectName: 'Certes'
      previewPackage: 'false'

  - template: scripts/pack.yml
    parameters:
      name: 'pack_tool_preview'
      displayName: 'Pack Certes.Tool preview'
      projectName: 'Certes.Cli'
      previewPackage: 'true'

  - template: scripts/pack.yml
    parameters:
      name: 'pack_tool'
      displayName: 'Pack Certes.Tool'
      projectName: 'Certes.Cli'
      previewPackage: 'false'
