
parameters:
  name: ''
  displayName: ''
  projectName: ''
  assemblyVersion: ''
  fileVersion: ''
  informationalVersion: ''

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'

  steps:
  
  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: 'custom'
      custom: 'pack'
      arguments: 'src/${{ parameters.projectName }}/${{ parameters.projectName }}.csproj --include-symbols -c Release'
    env:
      CERTES_ASSEMBLY_VERSION: ${{ parameters.assemblyVersion }}
      CERTES_FILE_VERSION: ${{ parameters.fileVersion }}
      CERTES_INFORMATIONAL_ASSEMBLYVERSION: ${{ parameters.informationalVersion }}

  - task: CopyFiles@2
    displayName: Copy nupkg
    inputs:
      Contents: 'src/${{ parameters.projectName }}/bin/**/*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: Publish nupkg
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '${{ parameters.name }}'
      publishLocation: 'Container'
